name: C/C++ CI

on:
  push:
    branches: [ "master" ]
    tags: [ "v[0-9]*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: ./dependencies.sh
    - name: fetch tags
      run: git fetch --tags ; git tag ; git for-each-ref ; git describe --always --abbrev=8 --tags ; git describe --always --abbrev=8 --tags --match 'v[0-9]*'
    - name: make
      run: make KVER='*'
    - name: make deb
      run: make deb
